config-version = "2.7"
bind = "0.0.0.0:25565"
motd = "<#09add3>A Minecraft Server @ Sekai Beyond 彼世界"
show-max-players = 50
online-mode = false
force-key-authentication = true
prevent-client-proxy-connections = false
player-info-forwarding-mode = "modern"
forwarding-secret-file = "forwarding.secret"
announce-forge = true
kick-existing-players = false
ping-passthrough = "DISABLED"
sample-players-in-ping = false
enable-player-address-logging = true

[servers]
lobby = "127.0.0.1:34565"
survival = "127.0.0.1:35565"
worldz = "127.0.0.1:36565"
try = [ "lobby" ]

[forced-hosts]
"mc.sekaibeyond.com" = [ "lobby" ]

[advanced]
compression-threshold = 256
compression-level = -1
login-ratelimit = 3_000
connection-timeout = 5_000
read-timeout = 30_000
haproxy-protocol = false
tcp-fast-open = false
bungee-plugin-message-channel = true
show-ping-requests = false
failover-on-unexpected-server-disconnect = true
announce-proxy-commands = true
log-command-executions = false
log-player-connections = true
accepts-transfers = false
enable-reuse-port = false
command-rate-limit = 50
forward-commands-if-rate-limited = true
kick-after-rate-limited-commands = 0
tab-complete-rate-limit = 10
kick-after-rate-limited-tab-completes = 0

[query]
enabled = false
port = 25_565
map = "Velocity"
show-plugins = false
